- name: 事前情報取得用ディレクトリ作成
  file:
    path: "/tmp/{{ inventory_hostname }}_patchinfo/bf"
    state: directory
    mode: '0755'

- name: 事前CPU使用率確認
  command: sar -u
  register: cpu_usage
  changed_when: false

- name: CPU使用率結果保存
  copy:
    content: "{{ cpu_usage.stdout }}\n"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/pre_cpu_usage.txt"
    mode: '0644'

- name: 事前メモリ使用率確認
  ansible.builtin.shell: >
    LANG=C; sar -r 1 1 |
    grep -vE "Linux|kbmemfree|^$|Average" |
    awk '{print $1, $5}'
  register: mem_usage
  changed_when: false

- name: 事前メモリ使用率結果保存
  ansible.builtin.copy:
    content: "{{ mem_usage.stdout }}\n"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/mem_usage.txt"
    mode: '0644'

- name: 事前ディスク使用率確認
  command: df -h
  register: disk_usage
  changed_when: false

- name: ディスク使用率結果保存
  copy:
    content: "{{ disk_usage.stdout }}\n"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/pre_disk_usage.txt"
    mode: '0644'
