- name: プロセス状態確認
  command: /usr/local/sam/kanshi/shell/sk_proc_dsp.sh
  register: process_status
  changed_when: false

- name: プロセス状態確認結果保存
  copy:
    content: "{{ process_status.stdout }}\n"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/process_status.txt"
    mode: '0644'

- name: カーネルバージョン確認
  command: uname -r
  register: kernel_version
  changed_when: false

- name: カーネルバージョン結果保存
  copy:
    content: "{{ kernel_version.stdout }}\n"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/kernel_version.txt"
    mode: '0644'

- name: サービス自動起動設定確認
  shell: >
    systemctl list-unit-files | grep -Ev '\.(scope|slice)'
  register: unit_files
  changed_when: false

- name: サービス自動起動設定結果保存
  copy:
    content: "{{ unit_files.stdout }}\n"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/unit-files_before"
    mode: '0644'

- name: Javaディレクトリ存在確認
  ansible.builtin.stat:
    path: /usr/lib/jvm
  register: jvm_dir

- name: Java関連ファイル確認・保存ブロック
  when: jvm_dir.stat.exists
  block:
    - name: Java関連ファイル確認
      ansible.builtin.command: ls -l /usr/lib/jvm
      register: java_info
      changed_when: false

    - name: Java関連ファイル結果保存
      ansible.builtin.copy:
        content: "{{ java_info.stdout }}\n"
        dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/java_info.txt"
        mode: '0644'
