- name: 事前情報取得用ディレクトリ作成
  file:
    path: "/tmp/{{ inventory_hostname }}_patchinfo/bf"
    state: directory
    mode: '0755'

- name: 事前CPU使用率確認
  command: sar -u
  register: cpu_usage
  changed_when: false

- name: CPU使用率結果保存
  copy:
    content: "{{ cpu_usage.stdout }}"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/pre_cpu_usage.txt"
    mode: '0644'

- name: 事前メモリ使用率確認
  shell: >
    LANG=C;
    sar -r -s hh:mm -f /var/log/sa/sa$(date '+%Y%m%d')
    | grep -vE "Linux|kbmemfree|$^"
    | awk '{printf "%s %4.2f\n", $1, (($2 + $4 - $3) * 100) / ($2 + $4)}'
    | cut -c -5,9-
  register: memory_usage
  changed_when: false

- name: メモリ使用率結果保存
  copy:
    content: "{{ memory_usage.stdout }}"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/pre_memory_usage.txt"
    mode: '0644'

- name: 事前ディスク使用率確認
  command: df -h
  register: disk_usage
  changed_when: false

- name: ディスク使用率結果保存
  copy:
    content: "{{ disk_usage.stdout }}"
    dest: "/tmp/{{ inventory_hostname }}_patchinfo/bf/pre_disk_usage.txt"
    mode: '0644'
